# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: tileserver-pvc
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 10Gi
#   volumeName: tileserver-pv # Explicitly bind to the PV
#   storageClassName: fast-ssd    # Match the PV's storageClassName


--- 
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tileserver-pvc-coastal
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Gi
  volumeName: tileserver-pv-coastal  # Explicitly bind to the PV
  storageClassName: fast-ssd    # Match the PV's storageClassName


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tileserver-pvc-admin
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  volumeName: tileserver-pv-admin  # Explicitly bind to the PV
  storageClassName: fast-ssd    # Match the PV's storageClassName


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tileserver-pvc-road
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  volumeName: tileserver-pv-road # Explicitly bind to the PV
  storageClassName: fast-ssd    # Match the PV's storageClassName

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tileserver-pvc-deduce
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  volumeName: tileserver-pv-deduce  # Explicitly bind to the PV
  storageClassName: fast-ssd    # Match the PV's storageClassName

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tileserver-pvc-deduce1
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  volumeName: tileserver-pv-deduce1  # Explicitly bind to the PV
  storageClassName: fast-ssd    # Match the PV's storageClassName

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tileserver-pvc-cache
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi  # Ensure it matches with the PV size
  volumeName: tileserver-pv-cache
  storageClassName: fast-ssd  # Ensure it matches with the PV storageClassName
